steal.plugins("jquery/controller",
              "jquery/event/drag", 
              "jquery/dom/within",
              "ss/controller/state_machine")
   .resources("jquery.ui.position")
 .controllers("tile",
              "large_zoom",
              "medium_zoom",
              "small_zoom",
              "control")
